# Generated by Django 4.1 on 2022-08-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=300, null=True)),
                ("url", models.URLField(max_length=300, null=True)),
                ("replies", models.TextField(max_length=300, null=True)),
                ("views", models.TextField(max_length=300, null=True)),
                ("date", models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=300, null=True)),
                ("url", models.URLField(max_length=300, null=True)),
                ("comments", models.TextField(max_length=300, null=True)),
                ("description", models.TextField(max_length=300, null=True)),
                ("date", models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecentPodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=300, null=True)),
                ("url", models.URLField(max_length=300, null=True)),
                ("date", models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SinglePodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=300, null=True)),
                ("audio_link", models.TextField(max_length=300, null=True)),
                ("description", models.TextField(null=True)),
                ("date", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField(max_length=300, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeglobal_api.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=300, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeglobal_api.topic",
                    ),
                ),
            ],
        ),
    ]
