# Generated by Django 4.0.6 on 2022-07-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.TextField(max_length=300, null=True)),
                ('Title', models.TextField(max_length=300, null=True)),
                ('Articleurl', models.TextField(max_length=300, null=True)),
                ('Replies', models.TextField(max_length=300, null=True)),
                ('Views', models.TextField(max_length=300, null=True)),
                ('Date', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicID', models.TextField(max_length=300, null=True)),
                ('Topic', models.TextField(max_length=300, null=True)),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeglobal_api.article')),
            ],
        ),
        migrations.CreateModel(
            name='TopicURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicUrlID', models.TextField(max_length=300, null=True)),
                ('TopicUrl', models.TextField(max_length=300, null=True)),
                ('TopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeglobal_api.topic')),
            ],
        ),
    ]
