# Generated by Django 4.0.6 on 2022-07-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeglobal_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='PodcastID',
        ),
        migrations.RemoveField(
            model_name='recentpodcast',
            name='RecentPodcastID',
        ),
    ]
