# Generated by Django 4.0.6 on 2022-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeglobal_api', '0002_person_species_delete_article_person_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_created', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
